asdf .= qwer()
asdf .= qwer
asdf .= 3
String|Integer asdf := 3
String|Integer asdf += 3
String|Integer asdf -= 3
String|Integer asdf *= 3
String|Integer asdf /= 3
String|Integer asdf %= 3
String|Integer asdf &= 3
String|Integer asdf |= 3
String|Integer asdf ^= 3
String|Integer asdf &&= 3
String|Integer asdf ||= 3
String|Integer asdf := qwer
String|Integer asdf += qwer
String|Integer asdf -= qwer
String|Integer asdf *= qwer
String|Integer asdf /= qwer
String|Integer asdf %= qwer
String|Integer asdf &= qwer
String|Integer asdf |= qwer
String|Integer asdf ^= qwer
String|Integer asdf &&= qwer
String|Integer asdf ||= qwer
String|Integer asdf := qwer()
String|Integer asdf += qwer()
String|Integer asdf -= qwer()
String|Integer asdf *= qwer()
String|Integer asdf /= qwer()
String|Integer asdf %= qwer()
String|Integer asdf &= qwer()
String|Integer asdf |= qwer()
String|Integer asdf ^= qwer()
String|Integer asdf &&= qwer()
String|Integer asdf ||= qwer()