Adfkljgh9879847564 asdf
A_fdghkourty456456 asdf
UPPER_CASE_987534 sdaf
String asdf
String<Value> asdg
String<Value...> sdgh
String<Key,Decimal>  tyuryu
String<Key,Decimal,Float...> rtghjedrfth
String<Key|Value,Decimal,Float...> reyhewrt
String<Key|Value,Float|Decimal,String...> ertysdfgsd
